### ISSUE TITLE
AttributeError: 'str' object has no attribute 'isoformat'

### ISSUE THREAD

**Issue by sebastian-philipp** [mikeckennedy/restful-services-in-pyramid#3]
Got this exceptions after clicking on the `GET /api/autos`  link:
```
(env) ➜  02_final_svc4_view_models_auto_service git:(master) pserve development.ini
Starting server in PID 30341.
Serving on http://localhost:6543
Serving on http://ip6-localhost:6543
2018-01-24 10:26:30,055 ERROR [pyramid_debugtoolbar:257][waitress] Squashed Exception at http://localhost:6543/static/theme.css'
traceback url: http://localhost:6543/_debug_toolbar/313430363931343738363330373532/exception
Traceback (most recent call last):
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/env/lib/python3.5/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/env/lib/python3.5/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/env/lib/python3.5/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/env/lib/python3.5/site-packages/pyramid/viewderivers.py", line 410, in viewresult_to_response
    result = view(context, request)
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/env/lib/python3.5/site-packages/pyramid/static.py", line 125, in __call__
    raise HTTPNotFound(request.url)
pyramid.httpexceptions.HTTPNotFound: http://localhost:6543/static/theme.css'
2018-01-24 10:26:38,154 ERROR [pyramid_debugtoolbar:267][waitress] Uncaught Exception at http://localhost:6543/api/autos
traceback url: http://localhost:6543/_debug_toolbar/313430363931343738323137303030/exception
Traceback (most recent call last):
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/env/lib/python3.5/site-packages/pyramid/tweens.py", line 12, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/env/lib/python3.5/site-packages/pyramid/view.py", line 756, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/env/lib/python3.5/site-packages/pyramid_debugtoolbar/toolbar.py", line 247, in toolbar_tween
    response = _handler(request)
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/env/lib/python3.5/site-packages/pyramid_debugtoolbar/panels/performance.py", line 58, in resource_timer_handler
    result = handler(request)
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/env/lib/python3.5/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/env/lib/python3.5/site-packages/pyramid/tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/env/lib/python3.5/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/env/lib/python3.5/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/env/lib/python3.5/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/env/lib/python3.5/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/env/lib/python3.5/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/env/lib/python3.5/site-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/env/lib/python3.5/site-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/env/lib/python3.5/site-packages/pyramid/viewderivers.py", line 462, in rendered_view
    request, result, view_inst, context)
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/env/lib/python3.5/site-packages/pyramid/renderers.py", line 435, in render_view
    return self.render_to_response(response, system, request=request)
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/env/lib/python3.5/site-packages/pyramid/renderers.py", line 458, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/env/lib/python3.5/site-packages/pyramid/renderers.py", line 454, in render
    result = renderer(value, system_values)
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/restful_auto_service/renderers/negotiate_renderer.py", line 27, in _render
    return renderer(self.info)(value, system)
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/env/lib/python3.5/site-packages/pyramid/renderers.py", line 277, in _render
    return self.serializer(value, default=default, **self.kw)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 200, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.5/json/encoder.py", line 427, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib/python3.5/json/encoder.py", line 324, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/env/lib/python3.5/site-packages/pyramid/renderers.py", line 291, in default
    return result(obj, request)
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/restful_auto_service/__init__.py", line 75, in <lambda>
    negotiate_renderer.add_adapter(Car, lambda c, _: c.to_dict())
  File "/home/sebastian/Repos/restful-services-in-pyramid/src/view_models/02_final_svc4_view_models_auto_service/restful_auto_service/data/car.py", line 19, in to_dict
    'last_seen': self.last_seen.isoformat(),
AttributeError: 'str' object has no attribute 'isoformat'

```

**Comment by mikeckennedy** [comment]
Hi,

The underlying error here is this:

`pyramid.httpexceptions.HTTPNotFound: The resource could not be found.`

because

`pyramid.httpexceptions.HTTPNotFound: http://localhost:6543/static/theme.css'`

Why the isoformat issue? Not sure. `self.last_seen ` is supposed to be a datetime but is a string in your code. Is this you running the exact code from this repo or your written version following along?

Best,
Michael

**Comment by sebastian-philipp** [comment]
> Is this you running the exact code from this repo or your written version following along?

I haven't touched anything. git clone, followed the readme and clicked on the link.

**Comment by mikeckennedy** [comment]
Got it, should be fixed now. Thanks for the heads up. 

Not sure what is up with the CSS 404 "error" because the link seems to render CSS content.
